### ISSUE TITLE
The specified interactions endpoint url could not be verified.

### ISSUE THREAD

**Issue by Sampo2910** [jsumners/nodebb-plugin-sso-discord-alt#14]
**_The specified interactions endpoint url could not be verified._**

Nothing is working having followed your instructions. What else do we have to do??

**Comment by jsumners** [comment]
No such error phrase exists in the code of this repository. Without a clearer description of the problem, or logs, I cannot provide any other assistance.

**Comment by Sampo2910** [comment]
Hi, In the readme it states what the URL should end in. Am I to assume that that is supposed to go on the end of my forum URL? When I put that in whilst creating the discord app that’s the error I get. Probably I’m doing wrong. The readme does not really give a proper explanation how to install/create in Discord.

**Comment by jsumners** [comment]
The readme tells you to create an application with Discord and to verify what that application's URL looks like.

**Comment by Sampo2910** [comment]
Does not help me. It’s not explained properly enough. Creating the app does not give a URL.. you have to input it yourself. I asked what am I doing wrong but your answer is as much use as a chocolate fireguard. Thanks. Take Care.

**Comment by Sampo2910** [comment]
Haha…. If you develop something at least have the decency to give support!!! Not sit their on your high horse. Pathetic.
