### ISSUE TITLE
Discord logo on login

### ISSUE THREAD

**Issue by G0wd** [jsumners/nodebb-plugin-sso-discord-alt#2]
Hello,

Is it possible to show the Discord logo on the login page instead of the pipper one?

Thanks in advance for the help.

**Comment by jsumners** [comment]
Only if this issue gets up voted and resolved -- https://github.com/FortAwesome/Font-Awesome/issues/7574

**Comment by G0wd** [comment]
Alright, I voted!

**Comment by Electromaster232** [comment]
Says it will be included in Font Awesome 5, so

**Comment by jsumners** [comment]
So this can't be resolved until https://github.com/FortAwesome/Font-Awesome/milestone/13 is complete.

**Comment by TobiTenno** [comment]
It's included in [font-awesome 5](https://fontawesome.com/icons/discord?style=brands), so now the wait is for nodebb to update.

**Comment by jsumners** [comment]
Thank you. It's probably going to be another couple weeks before I can get to this.

**Comment by TobiTenno** [comment]
No problem, I think we'll have to wait for nodebb to update their dependencies first. If I don't see a pr this weekend, I might go set up an instance and submit a proposal.
