### ISSUE TITLE
Auth Always makes new account (users can't link existing Node accounts with Discord)

### ISSUE THREAD

**Issue by Electromaster232** [jsumners/nodebb-plugin-sso-discord-alt#7]
Whenever a user attempts to link their current NodeBB account with Discord, it always opens a new NodeBB account, It seems to be impossible for users to avoid this.
https://theendlessweb.com

**Comment by jsumners** [comment]
https://github.com/jsumners/nodebb-plugin-sso-discord-alt/blob/master/library.js#L151

The plugin is using the NodeBB API to determine if an account already exists. If so, it is supposed to use the existing account. I would need more information about your problem before I can diagnose it.

At the very least, what version of NodeBB are you using?

Log messages would also help.

**Comment by Electromaster232** [comment]
Right sorry, using Node 1.6 erm lemme check for log stuff:
Nothing seems to be appearing in the logs.
@jsumners

**Comment by Electromaster232** [comment]
the issue seems to have disappeared, i'm not sure why nothing has changed. But im glad it did, thanks for the amazing plugin 😉

**Comment by jsumners** [comment]
I'm glad it sorted itself out 😀.
